Style/SignalException:
  EnforcedStyle: semantic

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/NumericLiteralPrefix:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Max: 120
